import {expect} from 'chai';
import {describe,it} from 'mocha';
import {ParameterizedQuery} from '../../../../src/core/modules/query/ParameterizedQuery.js';
import {JDBCConnectionFactory} from '../../../../src/core/modules/connection/JDBCConnectionFactory.js';

describe('Generated identity session regression',()=>{
    it('returns each inserted BIGINT identity despite alternating sessions',async()=>{
        const factory=new JDBCConnectionFactory();await factory.initialize({} as any);
        const query:any=new ParameterizedQuery();
        try{
            const config={url:'jdbc:hsqldb:mem:parameter_identity',autoCommit:true,readOnly:false,timeoutMs:1000};
            const sessions=[await factory.createConnection(config),await factory.createConnection(config)];
            await sessions[0].execute('CREATE TABLE IDENTITY_REGRESSION (ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 9007199254740992), VALUE INTEGER)');
            let next=0;let released=0;
            query._initialized=true;query.config={enableInjectionDetection:false,enableParameterValidation:true,maxParametersPerQuery:10,enableStatementCaching:false,defaultTimeoutMs:1000};
            query.connectionManager={getConnection:async()=>sessions[next++%2],releaseConnection:async()=>released++};
            for(const [value,identity] of [[1,'9007199254740992'],[2,'9007199254740993']]){
                const result=await query.execute('INSERT INTO IDENTITY_REGRESSION(VALUE) VALUES(?)',[value],{returnGeneratedIdentity:true,timeoutMs:1000});
                expect(String(result.generatedIdentity)).to.equal(identity);expect(result.affectedRows).to.equal(1);
            }
            expect(next).to.equal(2);expect(released).to.equal(2);
        }finally{await query.destroy();await factory.destroy();}
    });
});
