import { expect } from 'chai';
import { readFileSync, readdirSync } from 'node:fs';
import { ModelClasses } from '../../src/tables/index.js';

const javaDirectory = new URL('../../docs/starmade%20src/tables/', import.meta.url);

/** Validate model metadata against the supplied game's table definitions. */
describe('StarMade Java schema contract', () => {
    for (const file of readdirSync(javaDirectory).filter(file => file.endsWith('.java'))) {
        const source = readFileSync(new URL(file, javaDirectory), 'utf8');
        const table = source.match(/super\("([A-Z_]+)"/)?.[1];
        if (!table || !(table in ModelClasses)) continue;
        const model = ModelClasses[table as keyof typeof ModelClasses];
        const declarations = [...source.matchAll(/addColumn\("([A-Z_]+)",\s*([^;]+)\);/g)];
        it(`${table} exposes exactly the columns declared by ${file}`, () => {
            expect(model.schema.columns.map(column => column.name).sort()).to.deep.equal(declarations.map(match => match[1]).sort());
        });
        it(`${table} marks only Java identity columns as generated`, () => {
            const expected = declarations.filter(match => /GENERATED BY DEFAULT AS IDENTITY/.test(match[2])).map(match => match[1]);
            expect(model.schema.columns.filter(column => column.autoIncrement).map(column => column.name)).to.deep.equal(expected);
        });
    }
    it('accepts a new player before HSQLDB assigns its identity', () => {
        const player = new ModelClasses.PLAYERS({ NAME: 'new_player', STARMADE_NAME: 'New Player', FACTION: 0, PERMISSION: 0 });
        expect(player.validate().errors.map(error => error.field)).not.to.include('ID');
    });
    it('requires the game-assigned mine ID', () => {
        const mine = new ModelClasses.MINES();
        expect(mine.validate().errors.map(error => error.field)).to.include('ID');
    });
});
