/**
 * @fileoverview Cache Optimizer Module
 * 
 * This file defines an intelligent cache optimization system that provides
 * advanced eviction strategies, automatic parameter tuning, predictive prefetching,
 * and machine learning-based cache management for optimal performance.
 * 
 * @author InitSysRev
 * @version 1.0.0
 */

import {
    ConfigurationError,
    ModuleAlreadyInitializedError,
    ModuleNotInitializedError,
    PerformanceError
} from '../../errors.js';
import { resourceCleaner } from '../../utils.js';
import { createModuleLogger, type ModuleLogger } from '../logging/Logger.js';
import type { BaseModule, HSQLManager } from '../../HSQLManager.js';
import {
    ModuleEventEmitterImpl,
    ModuleEvent,
    createEventData,
    type ModuleEventEmitter,
    type ModuleEventListener
} from '../../events.js';
import type { CacheManager, CacheEntry, CacheStats } from './CacheManager.js';

// =============================================================================
// INTERFACES AND TYPES
// =============================================================================

/**
 * @interface AccessPattern
 * @description Represents the analysis of access patterns for a specific cache key.
 */
export interface AccessPattern {
    /** The cache key being analyzed. */
    key: string;
    /** The frequency of access, typically measured in accesses per hour. */
    frequency: number;
    /** The timestamp of the last access. */
    lastAccessed: Date;
    /** The average time interval in milliseconds between accesses. */
    averageInterval: number;
    /** The trend of access frequency ('increasing', 'decreasing', or 'stable'). */
    trend: 'increasing' | 'decreasing' | 'stable';
    /** The predicted timestamp of the next access. */
    predictedNextAccess?: Date;
    /** The confidence level of the prediction, from 0 to 1. */
    predictionConfidence: number;
}

/**
 * @interface EvictionStrategy
 * @description Defines an eviction strategy and its current state.
 */
export interface EvictionStrategy {
    /** The human-readable name of the strategy. */
    name: string;
    /** The type of the eviction strategy (e.g., 'lru', 'lfu'). */
    type: 'lru' | 'lfu' | 'arc' | 'adaptive' | 'ml-based';
    /** The parameters used to configure the strategy. */
    parameters: Record<string, any>;
    /** A score from 0 to 1 indicating the strategy's effectiveness. */
    effectiveness: number;
    /** A flag indicating if the strategy is currently enabled. */
    enabled: boolean;
}

/**
 * @interface OptimizationRecommendation
 * @description Represents a single optimization recommendation generated by the optimizer.
 */
export interface OptimizationRecommendation {
    /** The type of optimization being recommended. */
    type: 'ttl-adjustment' | 'prefetch-suggestion' | 'eviction-tuning' | 'size-optimization' | 'warming-strategy';
    /** The priority of the recommendation. */
    priority: 'low' | 'medium' | 'high' | 'critical';
    /** A concise title for the recommendation. */
    title: string;
    /** A detailed description of the recommendation and its rationale. */
    description: string;
    /** The expected performance improvement as a percentage. */
    expectedImprovement: number;
    /** The estimated effort required to implement the recommendation. */
    effort: 'low' | 'medium' | 'high';
    /** A flag indicating if the recommendation can be applied automatically. */
    autoApplicable: boolean;
    /** The parameters required to apply the recommendation. */
    parameters: Record<string, any>;
    /** The confidence level of the recommendation, from 0 to 1. */
    confidence: number;
}

/**
 * @interface OptimizerConfig
 * @description Defines the configuration for the CacheOptimizer.
 */
export interface OptimizerConfig {
    /** If true, enables intelligent eviction strategies beyond basic LRU. */
    enableIntelligentEviction: boolean;
    /** If true, enables predictive prefetching of cache entries. */
    enablePredictivePrefetching: boolean;
    /** If true, enables dynamic adjustment of TTLs based on usage patterns. */
    enableDynamicTtl: boolean;
    /** If true, enables machine learning-based optimizations. */
    enableMachineLearning: boolean;
    /** The time window in milliseconds for analyzing access patterns. */
    analysisWindow: number;
    /** The minimum confidence level (0-1) required to auto-apply a recommendation. */
    autoApplyThreshold: number;
    /** The interval in milliseconds for running periodic optimization checks. */
    optimizationInterval: number;
    /** The sensitivity to memory pressure for triggering adaptive strategies. */
    memoryPressureSensitivity: number;
}

/**
 * @interface EfficiencyMetrics
 * @description A collection of metrics that measure the efficiency of the cache.
 */
export interface EfficiencyMetrics {
    /** An overall efficiency score from 0 to 100. */
    score: number;
    /** A score based on the cache's hit ratio. */
    hitRatioEfficiency: number;
    /** A score based on how effectively memory is being utilized. */
    memoryEfficiency: number;
    /** A score indicating how well TTLs are optimized. */
    ttlEfficiency: number;
    /** A score for the effectiveness of the current eviction strategy. */
    evictionEfficiency: number;
    /** A score indicating how well the cache behavior aligns with access patterns. */
    patternAlignment: number;
}

/**
 * @interface OptimizationInsights
 * @description Provides a comprehensive overview of the cache's optimization status.
 */
export interface OptimizationInsights {
    /** The current efficiency metrics of the cache. */
    efficiency: EfficiencyMetrics;
    /** A list of detected access patterns. */
    patterns: AccessPattern[];
    /** A list of all available and active eviction strategies. */
    strategies: EvictionStrategy[];
    /** A history of recently applied optimizations. */
    recentOptimizations: OptimizationRecommendation[];
    /** An analysis of performance trends over time. */
    trends: {
        hitRatio: { current: number; trend: 'improving' | 'degrading' | 'stable' };
        memoryUsage: { current: number; trend: 'improving' | 'degrading' | 'stable' };
        responseTime: { current: number; trend: 'improving' | 'degrading' | 'stable' };
    };
}

/**
 * @interface PrefetchSuggestion
 * @description Represents a suggestion to prefetch a specific cache key.
 */
export interface PrefetchSuggestion {
    /** The key to be prefetched. */
    key: string;
    /** The predicted time of the next access. */
    predictedAccessTime: Date;
    /** The confidence level of the prediction, from 0 to 1. */
    confidence: number;
    /** The priority of the prefetch suggestion. */
    priority: number;
    /** An optional function to load the data for the key. */
    loader?: () => Promise<any>;
}

// =============================================================================
// CACHE OPTIMIZER CLASS
// =============================================================================

/**
 * @class CacheOptimizer
 * @description An advanced cache optimization system that provides intelligent eviction strategies,
 * automatic parameter tuning, and machine learning-based cache management.
 * @implements {BaseModule}
 * @implements {ModuleEventEmitter<ModuleEvent>}
 */
export class CacheOptimizer implements BaseModule, ModuleEventEmitter<ModuleEvent> {
    /** 
     * The name of the module.
     * @public
     * @readonly
     * @type {string}
     */
    public readonly name = 'cache-optimizer';
    /** 
     * The version of the module.
     * @public
     * @readonly
     * @type {string}
     */
    public readonly version = '1.0.0';
    /** 
     * Indicates whether the module has been initialized.
     * @public
     * @readonly
     * @type {boolean}
     */
    public get isInitialized(): boolean { return this._initialized; }

    /** 
     * @private 
     * @type {boolean}
     */
    private _initialized = false;
    /** 
     * @private 
     * @type {HSQLManager | undefined}
     */
    private manager?: HSQLManager;
    /** 
     * @private 
     * @type {CacheManager | undefined}
     */
    private cacheManager?: CacheManager;
    /** 
     * @private 
     * @type {OptimizerConfig | undefined}
     */
    private config?: OptimizerConfig;
    /** 
     * @private 
     * @type {boolean}
     */
    private destroyed = false;
    /** 
     * @private 
     * @readonly
     * @type {number}
     */
    private readonly startTime = Date.now();
    /** 
     * @private 
     * @type {ModuleLogger}
     */
    private logger: ModuleLogger;
    /** 
     * @private 
     * @type {ModuleEventEmitterImpl<ModuleEvent>}
     */
    private eventEmitter: ModuleEventEmitterImpl<ModuleEvent>;

    /** 
     * @private 
     * @type {Map<string, AccessPattern>}
     */
    private accessPatterns: Map<string, AccessPattern> = new Map();
    /** 
     * @private 
     * @type {Array<{ key: string; timestamp: Date; hit: boolean }>}
     */
    private accessHistory: Array<{ key: string; timestamp: Date; hit: boolean }> = [];
    /** 
     * @private 
     * @type {Map<string, EvictionStrategy>}
     */
    private evictionStrategies: Map<string, EvictionStrategy> = new Map();
    /** 
     * @private 
     * @type {OptimizationRecommendation[]}
     */
    private optimizationHistory: OptimizationRecommendation[] = [];
    /** 
     * @private 
     * @type {NodeJS.Timeout | undefined}
     */
    private optimizationTimer?: NodeJS.Timeout;
    /** 
     * @private 
     * @type {object}
     */
    private performanceBaselines: {
        hitRatio: number;
        avgResponseTime: number;
        memoryEfficiency: number;
    } = {
        hitRatio: 0,
        avgResponseTime: 0,
        memoryEfficiency: 0
    };

    /**
     * Creates a new instance of the CacheOptimizer.
     */
    constructor() {
        this.logger = createModuleLogger('CacheOptimizer-v1.0');
        this.eventEmitter = new ModuleEventEmitterImpl(this.logger, 'CacheOptimizer');

        // Initialize event listeners for module events
        this.eventEmitter.initializeEvents(Object.values(ModuleEvent));
    }

    /**
     * Initializes the cache optimizer. This sets up the configuration and available
     * eviction strategies. The CacheManager must be set separately via `setCacheManager`.
     * @async
     * @param {HSQLManager} manager - The HSQLDB manager instance.
     * @returns {Promise<void>} A promise that resolves when initialization is complete.
     * @throws {ModuleAlreadyInitializedError} If the module is already initialized.
     * @throws {ConfigurationError} If the provided manager is invalid.
     */
    public async initialize(manager: HSQLManager): Promise<void> {
        if (this._initialized) {
            throw new ModuleAlreadyInitializedError('CacheOptimizer', {
                operation: 'initialize'
            });
        }

        if (!manager) {
            throw new ConfigurationError('Manager parameter is required', ['manager'], {
                operation: 'initialize'
            });
        }

        this.logger.info('Initializing CacheOptimizer v1.0', {
            operation: 'initialize'
        });

        this.manager = manager;
        this.buildConfiguration();
        this.initializeEvictionStrategies();
        
        this._initialized = true;
        resourceCleaner.register(this);
        
        this.logger.info('CacheOptimizer v1.0 initialized successfully', {
            operation: 'initialize-complete',
            enableIntelligentEviction: this.config?.enableIntelligentEviction,
            enablePredictivePrefetching: this.config?.enablePredictivePrefetching,
            optimizationInterval: this.config?.optimizationInterval,
            cacheManagerSet: this.cacheManager !== undefined
        });

        // Emit initialization event
        this.emit(ModuleEvent.INITIALIZED, createEventData('cache-optimizer-initialized', {
            enableIntelligentEviction: this.config?.enableIntelligentEviction,
            enablePredictivePrefetching: this.config?.enablePredictivePrefetching,
            strategiesLoaded: this.evictionStrategies.size
        }, this.name));
    }

    /**
     * Sets the CacheManager instance to be optimized. This must be called after
     * initialization and before using any optimization features.
     * @param {CacheManager} cacheManager - The CacheManager instance to optimize.
     * @throws {ModuleNotInitializedError} If the optimizer is not initialized.
     * @throws {ConfigurationError} If the provided CacheManager is invalid or not initialized.
     */
    public setCacheManager(cacheManager: CacheManager): void {
        if (!this._initialized) {
            throw new ModuleNotInitializedError('CacheOptimizer', 'set cache manager', {
                operation: 'set-cache-manager'
            });
        }

        if (!cacheManager) {
            throw new ConfigurationError('CacheManager parameter is required', ['cacheManager'], {
                operation: 'set-cache-manager'
            });
        }

        if (!cacheManager.isInitialized) {
            throw new ConfigurationError('CacheManager must be initialized', ['cacheManager'], {
                operation: 'set-cache-manager'
            });
        }

        this.cacheManager = cacheManager;
        
        // Establish performance baselines now that we have a cache manager
        this.establishPerformanceBaselines().catch(error => {
            this.logger.warn('Failed to establish performance baselines', {
                operation: 'set-cache-manager',
                error: error instanceof Error ? error.message : String(error)
            });
        });
        
        // Start optimization timer
        this.startOptimizationTimer();

        this.logger.info('CacheManager set for optimization', {
            operation: 'set-cache-manager',
            cacheManagerName: cacheManager.name,
            cacheManagerVersion: cacheManager.version
        });
    }

    /**
     * Builds the optimizer's configuration from the HSQLManager's settings.
     * @private
     * @throws {ConfigurationError} If the manager reference is not set.
     */
    private buildConfiguration(): void {
        if (!this.manager) {
            throw new ConfigurationError('Manager not set', ['manager'], {
                operation: 'build-config'
            });
        }

        const managerConfig = this.manager.getConfiguration();
        
        this.config = {
            enableIntelligentEviction: true,
            enablePredictivePrefetching: true,
            enableDynamicTtl: true,
            enableMachineLearning: false, // Disabled initially for simplicity
            analysisWindow: 3600000, // 1 hour
            autoApplyThreshold: 0.7, // 70% confidence
            optimizationInterval: 300000, // 5 minutes
            memoryPressureSensitivity: 0.8
        };

        this.logger.debug('Configuration built for CacheOptimizer', { 
            operation: 'build-config',
            config: this.config 
        });
    }

    /**
     * Initializes the set of available eviction strategies.
     * @private
     */
    private initializeEvictionStrategies(): void {
        // Basic LRU strategy (default)
        this.evictionStrategies.set('lru', {
            name: 'Least Recently Used',
            type: 'lru',
            parameters: {},
            effectiveness: 0.7,
            enabled: true
        });

        // LFU strategy
        this.evictionStrategies.set('lfu', {
            name: 'Least Frequently Used',
            type: 'lfu',
            parameters: { frequencyWindow: 3600000 },
            effectiveness: 0.6,
            enabled: false
        });

        // Adaptive Replacement Cache (ARC)
        this.evictionStrategies.set('arc', {
            name: 'Adaptive Replacement Cache',
            type: 'arc',
            parameters: { adaptationRate: 0.1 },
            effectiveness: 0.8,
            enabled: false
        });

        // Adaptive strategy
        this.evictionStrategies.set('adaptive', {
            name: 'Adaptive Multi-Strategy',
            type: 'adaptive',
            parameters: { 
                strategies: ['lru', 'lfu'],
                switchThreshold: 0.1
            },
            effectiveness: 0.75,
            enabled: false
        });

        this.logger.debug('Eviction strategies initialized', {
            operation: 'init-strategies',
            strategiesCount: this.evictionStrategies.size
        });
    }

    /**
     * Establishes initial performance baselines for future comparison.
     * @private
     * @async
     */
    private async establishPerformanceBaselines(): Promise<void> {
        if (!this.cacheManager) return;

        try {
            const stats = this.cacheManager.getStats();
            
            this.performanceBaselines = {
                hitRatio: stats.hitRatio,
                avgResponseTime: 0, // Would need PerformanceMonitor integration
                memoryEfficiency: stats.totalSizeBytes > 0 ? 
                    (stats.totalEntries / stats.totalSizeBytes) * 1000 : 0
            };

            this.logger.info('Performance baselines established', {
                operation: 'establish-baselines',
                baselines: this.performanceBaselines
            });
        } catch (error) {
            this.logger.warn('Failed to establish performance baselines', {
                operation: 'establish-baselines',
                error: error instanceof Error ? error.message : String(error)
            });
        }
    }

    /**
     * Starts the timer for periodic automatic optimization analysis.
     * @private
     */
    private startOptimizationTimer(): void {
        if (this.optimizationTimer) {
            clearInterval(this.optimizationTimer);
        }

        this.optimizationTimer = setInterval(() => {
            this.performAutomaticOptimization().catch(error => {
                this.logger.warn('Automatic optimization failed', {
                    operation: 'optimization-timer',
                    error: error instanceof Error ? error.message : String(error)
                });
            });
        }, this.config!.optimizationInterval);

        this.logger.debug('Optimization timer started', {
            operation: 'start-optimization-timer',
            interval: this.config!.optimizationInterval
        });
    }

    /**
     * Records a cache access event to be used for pattern analysis.
     * @param {string} key - The cache key that was accessed.
     * @param {boolean} hit - True if the access was a cache hit, false for a miss.
     */
    public recordAccess(key: string, hit: boolean): void {
        if (!this._initialized) return;

        const now = new Date();
        
        // Add to access history
        this.accessHistory.push({ key, timestamp: now, hit });
        
        // Maintain history window
        const cutoff = new Date(now.getTime() - this.config!.analysisWindow);
        this.accessHistory = this.accessHistory.filter(access => access.timestamp >= cutoff);
        
        // Update access pattern
        this.updateAccessPattern(key, now);
    }

    /**
     * Updates the access pattern analysis for a given key.
     * @private
     * @param {string} key - The cache key to update.
     * @param {Date} accessTime - The timestamp of the access.
     */
    private updateAccessPattern(key: string, accessTime: Date): void {
        let pattern = this.accessPatterns.get(key);
        
        if (!pattern) {
            pattern = {
                key,
                frequency: 1,
                lastAccessed: accessTime,
                averageInterval: 0,
                trend: 'stable',
                predictionConfidence: 0.1
            };
        } else {
            // Update frequency (accesses per hour)
            const keyAccesses = this.accessHistory.filter(a => a.key === key);
            const hoursInWindow = this.config!.analysisWindow / 3600000;
            pattern.frequency = keyAccesses.length / hoursInWindow;
            
            // Update average interval
            if (keyAccesses.length > 1) {
                const intervals: number[] = [];
                for (let i = 1; i < keyAccesses.length; i++) {
                    intervals.push(keyAccesses[i].timestamp.getTime() - keyAccesses[i - 1].timestamp.getTime());
                }
                pattern.averageInterval = intervals.reduce((sum, interval) => sum + interval, 0) / intervals.length;
            }
            
            // Predict next access
            if (pattern.averageInterval > 0) {
                pattern.predictedNextAccess = new Date(accessTime.getTime() + pattern.averageInterval);
                pattern.predictionConfidence = Math.min(keyAccesses.length / 10, 1); // More accesses = higher confidence
            }
        }
        
        pattern.lastAccessed = accessTime;
        this.accessPatterns.set(key, pattern);
    }

    /**
     * Analyzes cache performance and generates a list of optimization recommendations.
     * @async
     * @returns {Promise<OptimizationRecommendation[]>} An array of optimization recommendations.
     * @throws {ModuleNotInitializedError} If the optimizer is not initialized.
     * @throws {ConfigurationError} If the CacheManager has not been set.
     */
    public async analyzeAndOptimize(): Promise<OptimizationRecommendation[]> {
        if (!this._initialized) {
            throw new ModuleNotInitializedError('CacheOptimizer', 'analyze and optimize', {
                operation: 'analyze-optimize'
            });
        }

        if (!this.cacheManager) {
            throw new ConfigurationError('CacheManager not set. Call setCacheManager() first.', ['cacheManager'], {
                operation: 'analyze-optimize'
            });
        }

        this.logger.info('Starting cache analysis and optimization', {
            operation: 'analyze-optimize',
            patternsTracked: this.accessPatterns.size,
            historySize: this.accessHistory.length
        });

        const recommendations: OptimizationRecommendation[] = [];
        
        try {
            // Analyze current performance
            const currentStats = this.cacheManager.getStats();
            const efficiency = this.calculateEfficiencyMetrics(currentStats);
            
            // Generate TTL optimization recommendations
            recommendations.push(...await this.generateTtlOptimizations());
            
            // Generate eviction strategy recommendations
            recommendations.push(...await this.generateEvictionOptimizations(efficiency));
            
            // Generate prefetching recommendations
            recommendations.push(...await this.generatePrefetchingRecommendations());
            
            // Generate memory optimization recommendations
            recommendations.push(...await this.generateMemoryOptimizations(currentStats));
            
            // Sort by priority and expected improvement
            recommendations.sort((a, b) => {
                const priorityOrder = { 'critical': 4, 'high': 3, 'medium': 2, 'low': 1 };
                const priorityDiff = priorityOrder[b.priority] - priorityOrder[a.priority];
                if (priorityDiff !== 0) return priorityDiff;
                return b.expectedImprovement - a.expectedImprovement;
            });

            this.logger.info('Cache analysis completed', {
                operation: 'analyze-optimize-complete',
                recommendationsGenerated: recommendations.length,
                highPriorityCount: recommendations.filter(r => r.priority === 'high' || r.priority === 'critical').length
            });

            return recommendations;

        } catch (error) {
            this.logger.error('Cache optimization analysis failed', {
                operation: 'analyze-optimize-error',
                error: error instanceof Error ? error.message : String(error)
            });
            throw new PerformanceError('Cache optimization analysis failed', error as Error, 'CacheOptimizer');
        }
    }

    /**
     * Calculates the current cache efficiency metrics based on statistics.
     * @private
     * @param {CacheStats} stats - The current cache statistics.
     * @returns {EfficiencyMetrics} The calculated efficiency metrics.
     */
    private calculateEfficiencyMetrics(stats: CacheStats): EfficiencyMetrics {
        const hitRatioEfficiency = Math.min(stats.hitRatio * 100, 100);
        
        // Memory efficiency: entries per MB
        const memoryMB = stats.totalSizeBytes / (1024 * 1024);
        const memoryEfficiency = memoryMB > 0 ? Math.min((stats.totalEntries / memoryMB) / 100, 100) : 100;
        
        // TTL efficiency: based on expiration vs eviction ratio
        const totalRemovals = stats.evictionCount + stats.expirationCount;
        const ttlEfficiency = totalRemovals > 0 ? (stats.expirationCount / totalRemovals) * 100 : 75;
        
        // Eviction efficiency: based on hit ratio trends
        const evictionEfficiency = Math.max(hitRatioEfficiency - 10, 0); // Simplified calculation
        
        // Pattern alignment: how well access patterns match cache behavior
        const patternAlignment = this.calculatePatternAlignment();
        
        const score = (hitRatioEfficiency + memoryEfficiency + ttlEfficiency + evictionEfficiency + patternAlignment) / 5;
        
        return {
            score: Math.round(score),
            hitRatioEfficiency: Math.round(hitRatioEfficiency),
            memoryEfficiency: Math.round(memoryEfficiency),
            ttlEfficiency: Math.round(ttlEfficiency),
            evictionEfficiency: Math.round(evictionEfficiency),
            patternAlignment: Math.round(patternAlignment)
        };
    }

    /**
     * Calculates how well the current cache behavior aligns with observed access patterns.
     * @private
     * @returns {number} A pattern alignment score from 0 to 100.
     */
    private calculatePatternAlignment(): number {
        if (this.accessPatterns.size === 0) return 50; // Neutral score
        
        let alignmentScore = 0;
        let totalPatterns = 0;
        
        for (const pattern of this.accessPatterns.values()) {
            // High frequency patterns should be in cache
            const frequencyScore = Math.min(pattern.frequency / 10, 1) * 100;
            
            // Recent access patterns should have good prediction confidence
            const confidenceScore = pattern.predictionConfidence * 100;
            
            alignmentScore += (frequencyScore + confidenceScore) / 2;
            totalPatterns++;
        }
        
        return totalPatterns > 0 ? alignmentScore / totalPatterns : 50;
    }

    /**
     * Generates TTL optimization recommendations based on access patterns.
     * @private
     * @async
     * @returns {Promise<OptimizationRecommendation[]>} An array of TTL optimization recommendations.
     */
    private async generateTtlOptimizations(): Promise<OptimizationRecommendation[]> {
        const recommendations: OptimizationRecommendation[] = [];
        
        if (!this.config?.enableDynamicTtl) return recommendations;
        
        // Analyze patterns for TTL optimization
        for (const pattern of this.accessPatterns.values()) {
            if (pattern.averageInterval > 0 && pattern.predictionConfidence > 0.5) {
                const optimalTtl = pattern.averageInterval * 1.2; // 20% buffer
                
                recommendations.push({
                    type: 'ttl-adjustment',
                    priority: pattern.predictionConfidence > 0.8 ? 'high' : 'medium',
                    title: `Optimize TTL for key pattern: ${pattern.key}`,
                    description: `Adjust TTL to ${Math.round(optimalTtl / 1000)}s based on access interval of ${Math.round(pattern.averageInterval / 1000)}s`,
                    expectedImprovement: 15,
                    effort: 'low',
                    autoApplicable: true,
                    parameters: {
                        keyPattern: pattern.key,
                        recommendedTtl: optimalTtl,
                        currentInterval: pattern.averageInterval
                    },
                    confidence: pattern.predictionConfidence
                });
            }
        }
        
        return recommendations;
    }

    /**
     * Generates eviction strategy optimization recommendations based on efficiency metrics.
     * @private
     * @async
     * @param {EfficiencyMetrics} efficiency - The current cache efficiency metrics.
     * @returns {Promise<OptimizationRecommendation[]>} An array of eviction optimization recommendations.
     */
    private async generateEvictionOptimizations(efficiency: EfficiencyMetrics): Promise<OptimizationRecommendation[]> {
        const recommendations: OptimizationRecommendation[] = [];
        
        if (!this.config?.enableIntelligentEviction) return recommendations;
        
        // If hit ratio is low, recommend better eviction strategy
        if (efficiency.hitRatioEfficiency < 70) {
            const bestStrategy = this.findBestEvictionStrategy();
            
            recommendations.push({
                type: 'eviction-tuning',
                priority: efficiency.hitRatioEfficiency < 50 ? 'high' : 'medium',
                title: `Switch to ${bestStrategy.name} eviction strategy`,
                description: `Current hit ratio (${efficiency.hitRatioEfficiency}%) suggests ${bestStrategy.name} would be more effective`,
                expectedImprovement: (bestStrategy.effectiveness - 0.7) * 100,
                effort: 'medium',
                autoApplicable: false, // Strategy changes require careful consideration
                parameters: {
                    recommendedStrategy: bestStrategy.type,
                    currentEffectiveness: 0.7,
                    expectedEffectiveness: bestStrategy.effectiveness
                },
                confidence: 0.8
            });
        }
        
        return recommendations;
    }

    /**
     * Finds the best eviction strategy based on current access patterns.
     * @private
     * @returns {EvictionStrategy} The most suitable eviction strategy.
     */
    private findBestEvictionStrategy(): EvictionStrategy {
        // Analyze access patterns to determine best strategy
        const totalAccesses = this.accessHistory.length;
        const uniqueKeys = new Set(this.accessHistory.map(a => a.key)).size;
        
        // If high reuse rate, LRU is good
        const reuseRate = totalAccesses > 0 ? (totalAccesses - uniqueKeys) / totalAccesses : 0;
        
        if (reuseRate > 0.7) {
            return this.evictionStrategies.get('lru')!;
        } else if (reuseRate > 0.4) {
            return this.evictionStrategies.get('arc')!;
        } else {
            return this.evictionStrategies.get('adaptive')!;
        }
    }

    /**
     * Generates predictive prefetching recommendations based on access patterns.
     * @private
     * @async
     * @returns {Promise<OptimizationRecommendation[]>} An array of prefetching recommendations.
     */
    private async generatePrefetchingRecommendations(): Promise<OptimizationRecommendation[]> {
        const recommendations: OptimizationRecommendation[] = [];
        
        if (!this.config?.enablePredictivePrefetching) return recommendations;
        
        const prefetchCandidates = this.identifyPrefetchCandidates();
        
        if (prefetchCandidates.length > 0) {
            recommendations.push({
                type: 'prefetch-suggestion',
                priority: 'medium',
                title: `Enable predictive prefetching for ${prefetchCandidates.length} keys`,
                description: `Identified ${prefetchCandidates.length} keys with predictable access patterns for prefetching`,
                expectedImprovement: Math.min(prefetchCandidates.length * 5, 25),
                effort: 'medium',
                autoApplicable: false, // Prefetching needs data loaders
                parameters: {
                    candidates: prefetchCandidates.slice(0, 10), // Limit to top 10
                    totalCandidates: prefetchCandidates.length
                },
                confidence: 0.7
            });
        }
        
        return recommendations;
    }

    /**
     * Identifies suitable candidates for predictive prefetching.
     * @private
     * @returns {PrefetchSuggestion[]} An array of prefetch candidates.
     */
    private identifyPrefetchCandidates(): PrefetchSuggestion[] {
        const candidates: PrefetchSuggestion[] = [];
        
        for (const pattern of this.accessPatterns.values()) {
            if (pattern.predictionConfidence > 0.6 && 
                pattern.predictedNextAccess && 
                pattern.predictedNextAccess > new Date()) {
                
                candidates.push({
                    key: pattern.key,
                    predictedAccessTime: pattern.predictedNextAccess,
                    confidence: pattern.predictionConfidence,
                    priority: pattern.frequency * pattern.predictionConfidence
                });
            }
        }
        
        // Sort by priority (frequency * confidence)
        candidates.sort((a, b) => b.priority - a.priority);
        
        return candidates;
    }

    /**
     * Generates memory optimization recommendations based on current usage.
     * @private
     * @async
     * @param {CacheStats} stats - The current cache statistics.
     * @returns {Promise<OptimizationRecommendation[]>} An array of memory optimization recommendations.
     */
    private async generateMemoryOptimizations(stats: CacheStats): Promise<OptimizationRecommendation[]> {
        const recommendations: OptimizationRecommendation[] = [];
        
        const config = this.cacheManager?.getConfiguration();
        if (!config) return recommendations;
        
        const memoryUsageRatio = stats.totalSizeBytes / config.maxSizeBytes;
        
        // If memory usage is high, recommend optimization
        if (memoryUsageRatio > 0.8) {
            recommendations.push({
                type: 'size-optimization',
                priority: memoryUsageRatio > 0.95 ? 'critical' : 'high',
                title: 'Optimize cache memory usage',
                description: `Memory usage at ${Math.round(memoryUsageRatio * 100)}%. Consider increasing cache size or implementing compression.`,
                expectedImprovement: 20,
                effort: 'medium',
                autoApplicable: false,
                parameters: {
                    currentUsage: stats.totalSizeBytes,
                    maxSize: config.maxSizeBytes,
                    usageRatio: memoryUsageRatio,
                    recommendedAction: memoryUsageRatio > 0.95 ? 'increase-size' : 'enable-compression'
                },
                confidence: 0.9
            });
        }
        
        return recommendations;
    }

    /**
     * Applies a given optimization recommendation.
     * @async
     * @param {OptimizationRecommendation} recommendation - The recommendation to apply.
     * @returns {Promise<boolean>} True if the recommendation was applied successfully, false otherwise.
     * @throws {ModuleNotInitializedError} If the optimizer is not initialized.
     */
    public async applyRecommendation(recommendation: OptimizationRecommendation): Promise<boolean> {
        if (!this._initialized) {
            throw new ModuleNotInitializedError('CacheOptimizer', 'apply recommendation', {
                operation: 'apply-recommendation'
            });
        }

        this.logger.info('Applying optimization recommendation', {
            operation: 'apply-recommendation',
            type: recommendation.type,
            title: recommendation.title,
            confidence: recommendation.confidence
        });

        try {
            let applied = false;

            switch (recommendation.type) {
                case 'ttl-adjustment':
                    applied = await this.applyTtlOptimization(recommendation);
                    break;
                case 'eviction-tuning':
                    applied = await this.applyEvictionOptimization(recommendation);
                    break;
                case 'size-optimization':
                    applied = await this.applyMemoryOptimization(recommendation);
                    break;
                default:
                    this.logger.warn('Unknown recommendation type', {
                        operation: 'apply-recommendation',
                        type: recommendation.type
                    });
                    applied = false;
            }

            if (applied) {
                // Add to optimization history
                this.optimizationHistory.push({
                    ...recommendation,
                    parameters: {
                        ...recommendation.parameters,
                        appliedAt: new Date().toISOString()
                    }
                });

                // Trim history to last 100 optimizations
                if (this.optimizationHistory.length > 100) {
                    this.optimizationHistory = this.optimizationHistory.slice(-100);
                }

                this.emit(ModuleEvent.INITIALIZED, createEventData('optimization-applied', {
                    type: recommendation.type,
                    expectedImprovement: recommendation.expectedImprovement
                }, this.name));
            }

            return applied;

        } catch (error) {
            this.logger.error('Failed to apply optimization recommendation', {
                operation: 'apply-recommendation',
                type: recommendation.type,
                error: error instanceof Error ? error.message : String(error)
            });
            return false;
        }
    }

    /**
     * Applies a TTL optimization recommendation.
     * @private
     * @async
     * @param {OptimizationRecommendation} recommendation - The TTL recommendation to apply.
     * @returns {Promise<boolean>} True if the optimization was applied.
     */
    private async applyTtlOptimization(recommendation: OptimizationRecommendation): Promise<boolean> {
        // TTL optimization would require integration with CacheManager
        // For now, just log the recommendation
        this.logger.info('TTL optimization recommended', {
            operation: 'apply-ttl-optimization',
            parameters: recommendation.parameters
        });
        return true; // Placeholder
    }

    /**
     * Applies an eviction strategy optimization recommendation.
     * @private
     * @async
     * @param {OptimizationRecommendation} recommendation - The eviction recommendation to apply.
     * @returns {Promise<boolean>} True if the new strategy was enabled.
     */
    private async applyEvictionOptimization(recommendation: OptimizationRecommendation): Promise<boolean> {
        const strategyType = recommendation.parameters.recommendedStrategy;
        const strategy = this.evictionStrategies.get(strategyType);
        
        if (strategy) {
            // Disable current strategy
            for (const s of this.evictionStrategies.values()) {
                s.enabled = false;
            }
            
            // Enable recommended strategy
            strategy.enabled = true;
            
            this.logger.info('Eviction strategy changed', {
                operation: 'apply-eviction-optimization',
                newStrategy: strategy.name,
                type: strategyType
            });
            
            return true;
        }
        
        return false;
    }

    /**
     * Applies a memory optimization recommendation.
     * @private
     * @async
     * @param {OptimizationRecommendation} recommendation - The memory recommendation to apply.
     * @returns {Promise<boolean>} True if the optimization was applied.
     */
    private async applyMemoryOptimization(recommendation: OptimizationRecommendation): Promise<boolean> {
        // Memory optimization would require CacheManager configuration changes
        // For now, just log the recommendation
        this.logger.info('Memory optimization recommended', {
            operation: 'apply-memory-optimization',
            parameters: recommendation.parameters
        });
        return true; // Placeholder
    }

    /**
     * Retrieves a comprehensive set of optimization insights and metrics.
     * @async
     * @returns {Promise<OptimizationInsights>} An object containing optimization insights.
     * @throws {ModuleNotInitializedError} If the optimizer is not initialized.
     * @throws {ConfigurationError} If the CacheManager has not been set.
     */
    public async getOptimizationInsights(): Promise<OptimizationInsights> {
        if (!this._initialized) {
            throw new ModuleNotInitializedError('CacheOptimizer', 'get optimization insights', {
                operation: 'get-insights'
            });
        }

        if (!this.cacheManager) {
            throw new ConfigurationError('CacheManager not set. Call setCacheManager() first.', ['cacheManager'], {
                operation: 'get-insights'
            });
        }

        const stats = this.cacheManager.getStats();
        const efficiency = this.calculateEfficiencyMetrics(stats);
        
        return {
            efficiency,
            patterns: Array.from(this.accessPatterns.values()).slice(0, 20), // Top 20 patterns
            strategies: Array.from(this.evictionStrategies.values()),
            recentOptimizations: this.optimizationHistory.slice(-10), // Last 10 optimizations
            trends: {
                hitRatio: {
                    current: stats.hitRatio,
                    trend: this.calculateTrend('hitRatio', stats.hitRatio)
                },
                memoryUsage: {
                    current: stats.totalSizeBytes,
                    trend: this.calculateTrend('memoryUsage', stats.totalSizeBytes)
                },
                responseTime: {
                    current: 0, // Would need PerformanceMonitor integration
                    trend: 'stable'
                }
            }
        };
    }

    /**
     * Calculates the trend for a given metric based on its baseline.
     * @private
     * @param {string} metric - The name of the metric.
     * @param {number} current - The current value of the metric.
     * @returns {'improving' | 'degrading' | 'stable'} The calculated trend.
     */
    private calculateTrend(metric: string, current: number): 'improving' | 'degrading' | 'stable' {
        // Simplified trend calculation - would need historical data in real implementation
        const baseline = (this.performanceBaselines as any)[metric] || current;
        const change = (current - baseline) / baseline;
        
        if (Math.abs(change) < 0.05) return 'stable';
        
        // For hit ratio, higher is better; for memory usage, depends on context
        if (metric === 'hitRatio') {
            return change > 0 ? 'improving' : 'degrading';
        } else {
            return 'stable'; // Simplified
        }
    }

    /**
     * Performs an automatic optimization cycle, analyzing and applying high-confidence recommendations.
     * @private
     * @async
     */
    private async performAutomaticOptimization(): Promise<void> {
        try {
            const recommendations = await this.analyzeAndOptimize();
            
            // Apply high-confidence, auto-applicable recommendations
            for (const recommendation of recommendations) {
                if (recommendation.autoApplicable && 
                    recommendation.confidence >= this.config!.autoApplyThreshold) {
                    
                    await this.applyRecommendation(recommendation);
                }
            }
            
            if (recommendations.length > 0) {
                this.logger.debug('Automatic optimization completed', {
                    operation: 'automatic-optimization',
                    totalRecommendations: recommendations.length,
                    autoApplied: recommendations.filter(r => 
                        r.autoApplicable && r.confidence >= this.config!.autoApplyThreshold
                    ).length
                });
            }
            
        } catch (error) {
            this.logger.warn('Automatic optimization failed', {
                operation: 'automatic-optimization',
                error: error instanceof Error ? error.message : String(error)
            });
        }
    }

    /**
     * Gets the current configuration of the cache optimizer.
     * @returns {OptimizerConfig | undefined} A copy of the current configuration, or undefined if not initialized.
     */
    public getConfiguration(): OptimizerConfig | undefined {
        return this.config ? { ...this.config } : undefined;
    }

    /**
     * Destroys the cache optimizer, clearing all timers and data, and cleaning up resources.
     * @async
     * @returns {Promise<void>} A promise that resolves when destruction is complete.
     */
    public async destroy(): Promise<void> {
        if (this.destroyed) {
            return;
        }

        this.logger.info('Destroying CacheOptimizer', {
            operation: 'destroy'
        });
        
        this.destroyed = true;
        this._initialized = false;

        // Stop optimization timer
        if (this.optimizationTimer) {
            clearInterval(this.optimizationTimer);
            this.optimizationTimer = undefined;
        }

        // Clear data structures
        this.accessPatterns.clear();
        this.accessHistory = [];
        this.evictionStrategies.clear();
        this.optimizationHistory = [];

        // Clear references
        this.cacheManager = undefined;
        this.manager = undefined;

        // Cleanup event emitter
        this.eventEmitter.destroy();

        resourceCleaner.unregister(this);
        
        this.logger.info('CacheOptimizer destroyed successfully', {
            operation: 'destroy-complete',
            uptime: Date.now() - this.startTime
        });
    }

    /**
     * Adds a listener for a module event.
     * @param {ModuleEvent} event - The event to listen for.
     * @param {ModuleEventListener<ModuleEvent>} listener - The callback function.
     */
    public on(event: ModuleEvent, listener: ModuleEventListener<ModuleEvent>): void {
        this.eventEmitter.on(event, listener);
    }

    /**
     * Adds a one-time listener for a module event.
     * @param {ModuleEvent} event - The event to listen for.
     * @param {ModuleEventListener<ModuleEvent>} listener - The callback function.
     */
    public once(event: ModuleEvent, listener: ModuleEventListener<ModuleEvent>): void {
        this.eventEmitter.once(event, listener);
    }

    /**
     * Removes a listener for a module event.
     * @param {ModuleEvent} event - The event to stop listening to.
     * @param {ModuleEventListener<ModuleEvent>} listener - The listener to remove.
     */
    public off(event: ModuleEvent, listener: ModuleEventListener<ModuleEvent>): void {
        this.eventEmitter.off(event, listener);
    }

    /**
     * Emits a module event.
     * @param {ModuleEvent} event - The event to emit.
     * @param {any} [data] - The data payload for the event.
     */
    public emit(event: ModuleEvent, data?: any): void {
        this.eventEmitter.emit(event, data);
    }

    /**
     * Removes all listeners for a specific module event, or all listeners if no event is specified.
     * @param {ModuleEvent} [event] - The event to remove listeners from.
     */
    public removeAllListeners(event?: ModuleEvent): void {
        this.eventEmitter.removeAllListeners(event);
    }

    /**
     * Gets the number of listeners for a specific module event.
     * @param {ModuleEvent} event - The event to count listeners for.
     * @returns {number} The number of listeners.
     */
    public listenerCount(event: ModuleEvent): number {
        return this.eventEmitter.listenerCount(event);
    }

    /**
     * Gets an array of all module event names that have listeners.
     * @returns {ModuleEvent[]} An array of event names.
     */
    public eventNames(): ModuleEvent[] {
        return this.eventEmitter.eventNames();
    }
}