/**
 * @fileoverview FtlController Tests
 * @author InitSysRev
 * @version 1.0.0
 *
 * Schema:
 *   ID BIGINT GENERATED BY DEFAULT AS IDENTITY (auto-increment)
 *   FROM_X, FROM_Y, FROM_Z INTEGER NOT NULL
 *   FROM_X_LOC, FROM_Y_LOC, FROM_Z_LOC INTEGER NOT NULL
 *   FROM_UID VARCHAR(128) NOT NULL
 *   TO_X, TO_Y, TO_Z INTEGER NOT NULL
 *   TO_X_LOC, TO_Y_LOC, TO_Z_LOC INTEGER DEFAULT 0 NOT NULL
 *   TO_UID VARCHAR(128) NOT NULL
 *   TYPE INTEGER NOT NULL
 *   PERMISSION INTEGER NOT NULL
 */
import { describe, it, before, after } from 'mocha';
import { assert, expect } from 'chai';
import { FtlController } from '../../../src/tables/ftl/FtlController.js';
import { FtlModel, FtlType, FTL_PERMISSION_COMBINATIONS } from '../../../src/tables/ftl/FtlModel.js';
import { HSQLManager } from '../../../src/core/index.js';
import { ValidationError, ModuleNotInitializedError } from '../../../src/core/errors.js';

const TEST_CONFIG = {
    starmadeDir: './tests/sandbox', worldName: 'test_world',
    connection: { timeoutMs: 10000, maxRetries: 2, readOnly: false, autoCommit: true, maxConcurrentConnections: 5 },
    modules: { enableRelationshipAnalysis: false, enableQueryValidation: true, enableParameterizedQueries: true, enableAdvancedCaching: true, enableMetricsCollection: false, enableAutoReconnection: false, enableConnectionFactory: true },
    logging: { level: 'error' as const, enableConsole: false, enableFile: false, enableQueries: false, enableConnections: false, enablePerformance: false }
};

const createdIds: number[] = [];
let coordCounter = 200;

function makeFtlData(overrides: Partial<Record<string, any>> = {}): Partial<Record<string, any>> {
    const c = ++coordCounter;
    return {
        TYPE: FtlType.WARP_GATE,
        FROM_X: c, FROM_Y: 0, FROM_Z: 0,
        FROM_X_LOC: 0, FROM_Y_LOC: 0, FROM_Z_LOC: 0,
        FROM_UID: `ftl_from_${c}`,
        TO_X: -c, TO_Y: 0, TO_Z: 0,
        TO_X_LOC: 0, TO_Y_LOC: 0, TO_Z_LOC: 0,
        TO_UID: `ftl_to_${c}`,
        PERMISSION: FTL_PERMISSION_COMBINATIONS.NORMAL,
        ...overrides
    };
}

/** Helper: create a FTL record and find it by UID to get the auto-generated ID */
async function createAndFind(controller: FtlController, data: Partial<Record<string, any>>): Promise<FtlModel> {
    await controller.create(data);
    const uid = data.FROM_UID as string;
    const results = await controller.findAll({ skipCache: true, limit: 1 });
    // Find the most recent one matching our UID
    const all = await controller.findAll({ skipCache: true, limit: 1000 });
    const found = all.find(r => r.get('FROM_UID') === uid);
    if (!found) throw new Error(`Could not find created FTL record with FROM_UID=${uid}`);
    return found;
}

describe('FtlController', function () {
    this.timeout(30000);
    let manager: HSQLManager;
    let controller: FtlController;

    before(async () => {
        manager = new HSQLManager(TEST_CONFIG);
        await manager.initialize();
        controller = new FtlController();
        await controller.initialize(manager);
    });

    after(async () => {
        for (const id of createdIds) { try { await controller.delete(id); } catch { /* ignore */ } }
        await manager.destroy();
    });

    describe('Initialization', () => {
        it('should create instance', () => expect(controller).to.be.instanceOf(FtlController));
        it('should throw when not initialized', async () => {
            const ctrl = new FtlController();
            try { await ctrl.findAll(); assert.fail(); } catch (e) { expect(e).to.be.instanceOf(ModuleNotInitializedError); }
        });
    });

    describe('ftlExistsById()', () => {
        it('returns false for non-existent', async () => {
            expect(await controller.ftlExistsById(999999999)).to.be.false;
        });
        it('returns true for existing', async () => {
            const data = makeFtlData();
            const record = await createAndFind(controller, data);
            createdIds.push(record.getId());
            expect(await controller.ftlExistsById(record.getId())).to.be.true;
        });
    });

    describe('create()', () => {
        it('should create a warp gate and retrieve it', async () => {
            const data = makeFtlData();
            const record = await createAndFind(controller, data);
            createdIds.push(record.getId());
            expect(record).to.be.instanceOf(FtlModel);
            expect(Number(record.getId())).to.be.a('number').and.greaterThan(0);
        });
        it('should default PERMISSION to NORMAL when omitted', async () => {
            const data = makeFtlData();
            delete (data as any).PERMISSION;
            const record = await createAndFind(controller, data);
            createdIds.push(record.getId());
            expect(Number(record.get('PERMISSION'))).to.equal(FTL_PERMISSION_COMBINATIONS.NORMAL);
        });
        it('should throw if TYPE missing', async () => {
            const data = makeFtlData();
            delete (data as any).TYPE;
            try { await controller.create(data); assert.fail(); }
            catch (e) { expect(e).to.be.instanceOf(ValidationError); }
        });
    });

    describe('findAll()', () => {
        it('returns array', async () => {
            expect(await controller.findAll({ limit: 5 })).to.be.an('array');
        });
        it('filters by type WORM_HOLE', async () => {
            const data = makeFtlData({ TYPE: FtlType.WORM_HOLE });
            const record = await createAndFind(controller, data);
            createdIds.push(record.getId());
            const results = await controller.findByType(FtlType.WORM_HOLE, { limit: 50, skipCache: true });
            expect(results.length).to.be.greaterThan(0);
            results.forEach(f => expect(Number(f.get('TYPE'))).to.equal(FtlType.WORM_HOLE));
        });
        it('filters by FROM_X/Y/Z sector', async () => {
            const data = makeFtlData({ FROM_X: 500, FROM_Y: 501, FROM_Z: 502 });
            const record = await createAndFind(controller, data);
            createdIds.push(record.getId());
            const results = await controller.findFromSector(500, 501, 502);
            expect(results.length).to.be.greaterThan(0);
        });
        it('filters by TO_X/Y/Z sector', async () => {
            const data = makeFtlData({ TO_X: 503, TO_Y: 504, TO_Z: 505 });
            const record = await createAndFind(controller, data);
            createdIds.push(record.getId());
            const results = await controller.findToSector(503, 504, 505);
            expect(results.length).to.be.greaterThan(0);
        });
    });

    describe('update()', () => {
        it('should update permission', async () => {
            const data = makeFtlData();
            const record = await createAndFind(controller, data);
            createdIds.push(record.getId());
            const updated = await controller.update(record.getId(), { PERMISSION: FTL_PERMISSION_COMBINATIONS.PEACE_ZONE });
            expect(Number(updated.get('PERMISSION'))).to.equal(FTL_PERMISSION_COMBINATIONS.PEACE_ZONE);
        });
        it('throws for invalid permission > 63', async () => {
            const data = makeFtlData();
            const record = await createAndFind(controller, data);
            createdIds.push(record.getId());
            try { await controller.update(record.getId(), { PERMISSION: 200 }); assert.fail(); }
            catch (e) { expect(e).to.be.instanceOf(ValidationError); }
        });
    });

    describe('delete()', () => {
        it('returns false for non-existent', async () => {
            expect(await controller.delete(999999999)).to.be.false;
        });
        it('deletes existing record', async () => {
            const data = makeFtlData();
            const record = await createAndFind(controller, data);
            expect(await controller.delete(record.getId())).to.be.true;
            expect(await controller.ftlExistsById(record.getId())).to.be.false;
        });
    });

    describe('bulkCreate()', () => {
        it('creates multiple records', async () => {
            const records = [makeFtlData(), makeFtlData()];
            const result = await controller.bulkCreate(records);
            expect(result.success).to.equal(2);
            // cleanup
            for (const r of records) {
                const all = await controller.findAll({ skipCache: true, limit: 1000 });
                const found = all.find(f => f.get('FROM_UID') === r.FROM_UID);
                if (found) createdIds.push(found.getId());
            }
        });
    });

    describe('getStatistics()', () => {
        it('returns valid stats', async () => {
            const stats = await controller.getStatistics();
            expect(stats).to.have.property('totalConnections').that.is.a('number');
            expect(stats).to.have.property('byType').that.is.an('object');
            expect(stats).to.have.property('peaceZoneCount').that.is.a('number');
            expect(stats).to.have.property('lockedCount').that.is.a('number');
            expect(stats).to.have.property('unrestrictedCount').that.is.a('number');
        });
    });
});
