/**
 * @fileoverview FleetMembersController Tests
 * @author InitSysRev
 * @version 1.0.0
 *
 * Schema:
 *   ID BIGINT GENERATED BY DEFAULT AS IDENTITY (auto-increment)
 *   FLEET_ID BIGINT NOT NULL -> FK FLEETS(ID)
 *   ENTITY_ID BIGINT NOT NULL -> FK ENTITIES(ID)
 *   MISSION_STRING VARCHAR(1024)
 *   LIST_INDEX INTEGER NOT NULL
 *   DOCKED_TO BIGINT NOT NULL
 *   FACTION INTEGER DEFAULT 0 NOT NULL
 *
 * Note: FLEET_ID and ENTITY_ID have real FK constraints in HSQLDB.
 * Tests that create records use IDs fetched from existing DB data.
 */
import { describe, it, before, after } from 'mocha';
import { assert, expect } from 'chai';
import { FleetMembersController } from '../../../src/tables/fleet-members/FleetMembersController.js';
import { FleetMembersModel } from '../../../src/tables/fleet-members/FleetMembersModel.js';
import { FleetsController } from '../../../src/tables/fleets/FleetsController.js';
import { HSQLManager } from '../../../src/core/index.js';
import { ValidationError, ModuleNotInitializedError } from '../../../src/core/errors.js';

const TEST_CONFIG = {
    starmadeDir: './tests/sandbox', worldName: 'test_world',
    connection: { timeoutMs: 10000, maxRetries: 2, readOnly: false, autoCommit: true, maxConcurrentConnections: 5 },
    modules: { enableRelationshipAnalysis: false, enableQueryValidation: true, enableParameterizedQueries: true, enableAdvancedCaching: true, enableMetricsCollection: false, enableAutoReconnection: false, enableConnectionFactory: true },
    logging: { level: 'error' as const, enableConsole: false, enableFile: false, enableQueries: false, enableConnections: false, enablePerformance: false }
};

const createdFleetIds: number[] = [];
const createdKeys: Array<{ fleetId: number; entityId: number }> = [];

describe('FleetMembersController', function () {
    this.timeout(30000);
    let manager: HSQLManager;
    let controller: FleetMembersController;
    let fleetsCtrl: FleetsController;

    /** IDs to use for FK references – populated in before() */
    let existingEntityId: number = -1;
    let testFleetId: number = -1;

    before(async () => {
        manager = new HSQLManager(TEST_CONFIG);
        await manager.initialize();
        controller = new FleetMembersController();
        await controller.initialize(manager);
        fleetsCtrl = new FleetsController();
        await fleetsCtrl.initialize(manager);

        // The checked-in fixture must contain an entity for the real foreign keys.
        const paramQ = manager.getModule<any>('parameterized-query');
        expect(paramQ).to.exist;
        const result = await paramQ.execute('SELECT ID FROM ENTITIES ORDER BY ID LIMIT 1', []);
        expect(result.rows).not.to.be.empty;
        existingEntityId = Number(result.rows[0][0]);
        const fleet = await fleetsCtrl.create({
            FLAGSHIP_ID: existingEntityId,
            PARENT_FLEET: -1,
            NAME: 'Test Fleet for FleetMembers',
            OWNER: 'test_owner',
            MISSION_STRING: 'IDLE'
        });
        testFleetId = fleet.getId();
        createdFleetIds.push(testFleetId);
    });

    after(async () => {
        for (const k of createdKeys) { try { await controller.delete(k); } catch { /* ignore */ } }
        for (const id of createdFleetIds) { try { await fleetsCtrl.delete(id); } catch { /* ignore */ } }
        await manager.destroy();
    });

    describe('Initialization', () => {
        it('creates instance', () => expect(controller).to.be.instanceOf(FleetMembersController));
        it('throws when not initialized', async () => {
            const ctrl = new FleetMembersController();
            try { await ctrl.findAll(); assert.fail(); } catch (e) { expect(e).to.be.instanceOf(ModuleNotInitializedError); }
        });
    });

    describe('membershipExists()', () => {
        it('returns false for non-existent membership', async () => {
            try {
                expect(await controller.membershipExists(999999, 999998)).to.be.false;
            } catch (e) {
                // If manager not initialized (no entities in sandbox), skip gracefully
                if ((e as Error).message?.includes('not initialized') || (e as Error).message?.includes('Cannot')) {
                    return;
                }
                throw e;
            }
        });
        it('returns true for an existing membership with real foreign keys', async () => {
            const data = { FLEET_ID: testFleetId, ENTITY_ID: existingEntityId, MISSION_STRING: 'IDLE', LIST_INDEX: 0, DOCKED_TO: -1, FACTION: 0 };
            await controller.create(data);
            createdKeys.push({ fleetId: testFleetId, entityId: existingEntityId });
            expect(await controller.membershipExists(testFleetId, existingEntityId)).to.be.true;
            expect(await controller.delete({ fleetId: testFleetId, entityId: existingEntityId })).to.be.true;
        });
    });

    describe('create()', () => {
        it('throws ValidationError when FLEET_ID missing', async () => {
            try { await controller.create({ ENTITY_ID: 1, LIST_INDEX: 0, DOCKED_TO: -1 }); assert.fail(); }
            catch (e) { expect(e).to.be.instanceOf(ValidationError); }
        });
        it('throws ValidationError when ENTITY_ID missing', async () => {
            try { await controller.create({ FLEET_ID: 1, LIST_INDEX: 0, DOCKED_TO: -1 }); assert.fail(); }
            catch (e) { expect(e).to.be.instanceOf(ValidationError); }
        });
        it('creates a membership with valid FK IDs', async () => {
            const data = { FLEET_ID: testFleetId, ENTITY_ID: existingEntityId, MISSION_STRING: 'PATROLLING', LIST_INDEX: 1, DOCKED_TO: -1, FACTION: 0 };
            expect(await controller.membershipExists(testFleetId, existingEntityId)).to.be.false;
            const member = await controller.create(data, { preventDuplicates: true });
            createdKeys.push({ fleetId: testFleetId, entityId: existingEntityId });
            expect(member).to.be.instanceOf(FleetMembersModel);
            expect(member.getEntityId()).to.equal(existingEntityId);
        });
    });

    describe('findAll()', () => {
        for (const dockingStatus of ['FREE_FLOATING', 'DOCKED_TO_FLEET_MEMBER', 'DOCKED_TO_STATION', 'UNKNOWN']) {
            it('executes the schema-derived ' + dockingStatus + ' filter', async () => {
                const rows = await controller.findAll({ fleetId: testFleetId, dockingStatus: dockingStatus as any, flagshipOnly: true });
                expect(rows).to.be.an('array');
                if (dockingStatus === 'FREE_FLOATING') {
                    expect(rows.map(row => Number(row.getEntityId()))).to.include(existingEntityId);
                } else {
                    expect(rows).to.have.length(0);
                }
            });
        }

        it('should return an array', async () => {
            const results = await controller.findAll({ limit: 10 });
            expect(results).to.be.an('array');
        });
        it('should filter by FLEET_ID (empty is valid for unknown fleet)', async () => {
            const results = await controller.findAll({ fleetId: 999999 });
            expect(results).to.be.an('array');
        });
        it('should filter by ENTITY_ID (empty is valid for unknown entity)', async () => {
            const results = await controller.findByEntity(999998);
            expect(results).to.be.an('array');
        });
    });

    describe('delete()', () => {
        it('returns false for non-existent membership', async () => {
            expect(await controller.delete({ fleetId: 999999, entityId: 999998 })).to.be.false;
        });
    });

    describe('countByFleet()', () => {
        it('returns a number', async () => {
            const count = await controller.countByFleet(999999);
            expect(count).to.be.a('number').and.greaterThanOrEqual(0);
        });
    });

    describe('getStatistics()', () => {
        it('returns valid statistics', async () => {
            const stats = await controller.getStatistics();
            expect(stats).to.have.property('totalMembers').that.is.a('number');
            expect(stats).to.have.property('distinctFleets').that.is.a('number');
            expect(stats).to.have.property('distinctEntities').that.is.a('number');
            expect(stats).to.have.property('missionDistribution').that.is.an('object');
            expect(stats).to.have.property('averageMembersPerFleet').that.is.a('number');
            expect(stats).to.have.property('largestFleet');
        });
    });

    describe('bulkCreate()', () => {
        it('handles errors gracefully with continueOnError=true', async () => {
            // FK constraints will reject invalid IDs – result.failed > 0 is acceptable
            const records = [
                { FLEET_ID: 999990, ENTITY_ID: 999991, MISSION_STRING: 'IDLE', LIST_INDEX: 0, DOCKED_TO: -1, FACTION: 0 }
            ];
            const result = await controller.bulkCreate(records, { continueOnError: true });
            expect(result).to.have.property('success').that.is.a('number');
            expect(result).to.have.property('failed').that.is.a('number');
            expect(result.success + result.failed + result.skipped).to.equal(1);
        });
    });
});
