import java.sql.*;
import java.io.*;
import java.nio.file.*;

/**
 * SandboxLoader - Rebuilds the StarMade test database from scratch.
 * Creates all tables with the correct schema and inserts test data.
 */
public class SandboxLoader {
    public static void main(String[] args) throws Exception {
        String dbPath = args[1];
        String sqlDir = args[2];
        
        String url = "jdbc:hsqldb:file:" + dbPath + ";shutdown=true;hsqldb.lock_file=false;hsqldb.nio_data_file=false;hsqldb.write_delay=false;hsqldb.log_data=false";
        
        Class.forName("org.hsqldb.jdbc.JDBCDriver");
        System.out.println("Connecting to: " + url);
        
        try (Connection conn = DriverManager.getConnection(url, "SA", "")) {
            conn.setAutoCommit(true);
            System.out.println("Connected!");
            
            // Create schema
            exec(conn, "SET SCHEMA PUBLIC");
            createSchema(conn);

            // Load SQL data files
            String[] files = {
                "00-cleanup.sql", "01-systems.sql", "02-players.sql", "03-sectors.sql",
                "04-entities.sql", "05-fleets.sql", "06-fleet-members.sql", "07-ftl.sql",
                "08-trade-nodes.sql", "09-effects.sql", "10-mines.sql", "11-player-messages.sql",
                "12-sectors-items.sql", "13-trade-history.sql", "14-visibility.sql",
                "15-npc-stats.sql", "16-id-gen-table.sql"
            };
            
            for (String file : files) {
                Path p = Paths.get(sqlDir, file);
                if (!Files.exists(p)) { System.out.println("MISSING: " + file); continue; }
                
                String content = new String(Files.readAllBytes(p));
                String[] stmts = content.split(";");
                int ok = 0, skip = 0;
                
                for (String stmt : stmts) {
                    stmt = stmt.replaceAll("--[^\n]*", "").trim();
                    if (stmt.isEmpty()) continue;
                    if (stmt.toUpperCase().startsWith("SET FOREIGN_KEY_CHECKS")) { skip++; continue; }
                    if (stmt.toUpperCase().startsWith("SET ") && !stmt.toUpperCase().contains("SCHEMA")) { skip++; continue; }
                    
                    try (Statement s = conn.createStatement()) {
                        s.execute(stmt);
                        ok++;
                    } catch (SQLException e) {
                        String msg = e.getMessage();
                        boolean silent = msg.contains("already exists") || msg.contains("duplicate") 
                            || msg.contains("integrity") || msg.contains("Unique constraint")
                            || msg.contains("violation");
                        if (!silent && skip < 5) {
                            System.out.println("  ERR [" + file + "]: " + msg.substring(0, Math.min(120, msg.length())));
                        }
                        skip++;
                    }
                }
                System.out.println(file + ": " + ok + " OK, " + skip + " skipped");
            }
            
            // Count results
            String[] tables = {"SYSTEMS","PLAYERS","SECTORS","ENTITIES","EFFECTS","FLEETS","FLEET_MEMBERS",
                               "FTL","TRADE_NODES","MINES","PLAYER_MESSAGES","SECTORS_ITEMS",
                               "TRADE_HISTORY","VISIBILITY","NPC_STATS","ID_GEN_TABLE"};
            System.out.println("\n--- Row counts ---");
            for (String t : tables) {
                try (Statement s = conn.createStatement();
                     ResultSet rs = s.executeQuery("SELECT COUNT(*) FROM " + t)) {
                    rs.next();
                    System.out.println(t + ": " + rs.getInt(1) + " rows");
                } catch (SQLException e) {
                    System.out.println(t + ": ERROR - " + e.getMessage().substring(0, Math.min(80, e.getMessage().length())));
                }
            }
        }
        System.out.println("\nDone!");
    }

    static void exec(Connection conn, String sql) throws SQLException {
        try (Statement s = conn.createStatement()) { s.execute(sql); }
    }

    static void createSchema(Connection conn) throws SQLException {
        String[][] ddl = {
            // ID_GEN_TABLE
            {"CREATE CACHED TABLE IF NOT EXISTS ID_GEN_TABLE (ID VARCHAR(128) NOT NULL PRIMARY KEY, ID_GEN BIGINT NOT NULL)"},
            // PLAYERS
            {"CREATE CACHED TABLE IF NOT EXISTS PLAYERS (ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 2147483647) NOT NULL PRIMARY KEY, NAME VARCHAR(512) NOT NULL, STARMADE_NAME VARCHAR(512) NOT NULL, FACTION INTEGER DEFAULT 0 NOT NULL, PERMISSION BIGINT DEFAULT 0 NOT NULL)"},
            {"CREATE UNIQUE INDEX IF NOT EXISTS PLAYERS_NAME ON PLAYERS(NAME)"},
            {"CREATE INDEX IF NOT EXISTS PLAYERS_SM_NAME ON PLAYERS(STARMADE_NAME)"},
            // SYSTEMS
            {"CREATE CACHED TABLE IF NOT EXISTS SYSTEMS (ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY, X INTEGER NOT NULL, Y INTEGER NOT NULL, Z INTEGER NOT NULL, TYPE INTEGER NOT NULL, STARTTIME BIGINT, NAME VARCHAR(64), INFOS VARBINARY(8192) NOT NULL, OWNER_UID VARCHAR(128), OWNER_FACTION INTEGER DEFAULT 0 NOT NULL, OWNER_X INTEGER DEFAULT 0 NOT NULL, OWNER_Y INTEGER DEFAULT 0 NOT NULL, OWNER_Z INTEGER DEFAULT 0 NOT NULL, RESOURCES VARBINARY(16) NOT NULL)"},
            {"CREATE UNIQUE INDEX IF NOT EXISTS SYSCOORDINDEX ON SYSTEMS(X,Y,Z)"},
            {"CREATE INDEX IF NOT EXISTS SYSOWNFACINDEX ON SYSTEMS(OWNER_FACTION)"},
            {"CREATE INDEX IF NOT EXISTS SYSOWNUIDINDEX ON SYSTEMS(OWNER_UID)"},
            // SECTORS
            {"CREATE CACHED TABLE IF NOT EXISTS SECTORS (ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY, X INTEGER NOT NULL, Y INTEGER NOT NULL, Z INTEGER NOT NULL, TYPE INTEGER NOT NULL, NAME VARCHAR(64) NOT NULL, ITEMS BIGINT NOT NULL, PROTECTION INTEGER NOT NULL, STELLAR INTEGER NOT NULL, TRANSIENT BOOLEAN DEFAULT TRUE NOT NULL, LAST_REPLENISHED BIGINT DEFAULT 0 NOT NULL)"},
            {"CREATE UNIQUE INDEX IF NOT EXISTS SECCOORDINDEX ON SECTORS(X,Y,Z)"},
            // SECTORS_ITEMS
            {"CREATE CACHED TABLE IF NOT EXISTS SECTORS_ITEMS (ID BIGINT PRIMARY KEY, ITEMS VARBINARY(22528) NOT NULL)"},
            // ENTITIES (with proper ARRAY types)
            {"CREATE CACHED TABLE IF NOT EXISTS ENTITIES (UID VARCHAR(128) NOT NULL, X INTEGER NOT NULL, Y INTEGER NOT NULL, Z INTEGER NOT NULL, TYPE TINYINT NOT NULL, NAME CHARACTER(64), FACTION INTEGER DEFAULT 0, CREATOR VARCHAR(64), LAST_MOD VARCHAR(64), SEED BIGINT, TOUCHED BOOLEAN, LOCAL_POS DOUBLE ARRAY[3], DIM INTEGER ARRAY[6], GEN_ID INTEGER, DOCKED_TO BIGINT DEFAULT -1, DOCKED_ROOT BIGINT DEFAULT -1, SPAWNED_ONLY_IN_DB BOOLEAN DEFAULT FALSE, TRACKED BOOLEAN DEFAULT FALSE, ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY)"},
            {"CREATE UNIQUE INDEX IF NOT EXISTS UIDTYPE ON ENTITIES(UID,TYPE)"},
            {"CREATE INDEX IF NOT EXISTS ENTITIES_PK ON ENTITIES(UID)"},
            {"CREATE INDEX IF NOT EXISTS COORDINDEX ON ENTITIES(X,Y,Z)"},
            {"CREATE INDEX IF NOT EXISTS TYPEINDEX ON ENTITIES(TYPE)"},
            {"CREATE INDEX IF NOT EXISTS DOCKEDTOINDEX ON ENTITIES(DOCKED_TO)"},
            // EFFECTS
            {"CREATE CACHED TABLE IF NOT EXISTS EFFECTS (ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY, ENTITY_ID BIGINT NOT NULL, TYPE TINYINT NOT NULL, EFFECT_UID VARCHAR(128))"},
            {"CREATE INDEX IF NOT EXISTS EFFECTS_PK ON EFFECTS(ENTITY_ID)"},
            {"CREATE INDEX IF NOT EXISTS EFFECTS_TYPE ON EFFECTS(TYPE)"},
            // FTL
            {"CREATE CACHED TABLE IF NOT EXISTS FTL (ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY, FROM_X INTEGER NOT NULL, FROM_Y INTEGER NOT NULL, FROM_Z INTEGER NOT NULL, FROM_X_LOC INTEGER NOT NULL, FROM_Y_LOC INTEGER NOT NULL, FROM_Z_LOC INTEGER NOT NULL, FROM_UID VARCHAR(128) NOT NULL, TO_X INTEGER NOT NULL, TO_Y INTEGER NOT NULL, TO_Z INTEGER NOT NULL, TO_X_LOC INTEGER DEFAULT 0 NOT NULL, TO_Y_LOC INTEGER DEFAULT 0 NOT NULL, TO_Z_LOC INTEGER DEFAULT 0 NOT NULL, TO_UID VARCHAR(128) NOT NULL, TYPE INTEGER NOT NULL, PERMISSION INTEGER NOT NULL)"},
            // VISIBILITY
            {"CREATE CACHED TABLE IF NOT EXISTS VISIBILITY (ID BIGINT, X INTEGER NOT NULL, Y INTEGER NOT NULL, Z INTEGER NOT NULL, TIMESTAMP BIGINT, PRIMARY KEY(ID,X,Y,Z))"},
            // FLEETS
            {"CREATE CACHED TABLE IF NOT EXISTS FLEETS (ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY, FLAGSHIP_ID BIGINT NOT NULL, PARENT_FLEET BIGINT DEFAULT -1, NAME VARCHAR(128), OWNER VARCHAR(128), MISSION_STRING VARCHAR(1024), COMMAND VARBINARY(1024), FACTION_ACCESS TINYINT DEFAULT 0, SAVED_REMOTES VARBINARY(1024), COMBAT_SETTING VARCHAR(128))"},
            // FLEET_MEMBERS
            {"CREATE CACHED TABLE IF NOT EXISTS FLEET_MEMBERS (ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY, FLEET_ID BIGINT NOT NULL, ENTITY_ID BIGINT NOT NULL, MISSION_STRING VARCHAR(1024), LIST_INDEX INTEGER NOT NULL, DOCKED_TO BIGINT NOT NULL, FACTION INTEGER DEFAULT 0 NOT NULL, CONSTRAINT FFKC FOREIGN KEY(FLEET_ID) REFERENCES FLEETS(ID), CONSTRAINT EFKC FOREIGN KEY(ENTITY_ID) REFERENCES ENTITIES(ID))"},
            {"CREATE UNIQUE INDEX IF NOT EXISTS FMUNIQUEIDX ON FLEET_MEMBERS(FLEET_ID,ENTITY_ID)"},
            // TRADE_NODES (real StarMade schema)
            {"CREATE CACHED TABLE IF NOT EXISTS TRADE_NODES (ID BIGINT PRIMARY KEY, SEC_X INTEGER NOT NULL, SEC_Y INTEGER NOT NULL, SEC_Z INTEGER NOT NULL, PLAYER VARCHAR(128) NOT NULL, STATION_NAME VARCHAR(128) NOT NULL, FACTION INTEGER NOT NULL, PERMISSION BIGINT DEFAULT 15 NOT NULL, ITEMS VARBINARY(73732) NOT NULL, VOLUME DOUBLE NOT NULL, CAPACITY DOUBLE NOT NULL, CREDITS BIGINT NOT NULL)"},
            {"CREATE INDEX IF NOT EXISTS FACINDEX ON TRADE_NODES(FACTION)"},
            {"CREATE INDEX IF NOT EXISTS PLAYERINDEX ON TRADE_NODES(PLAYER)"},
            // TRADE_HISTORY
            {"CREATE CACHED TABLE IF NOT EXISTS TRADE_HISTORY (ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY, FROM_ID BIGINT NOT NULL, TO_ID BIGINT NOT NULL, FROM_OWNER VARCHAR(128) NOT NULL, TO_OWNER VARCHAR(128) NOT NULL, FROM_FACTION_ID INTEGER NOT NULL, TO_FACTION_ID INTEGER NOT NULL, TOTAL_COST BIGINT NOT NULL, DELIVERY_COST BIGINT NOT NULL, SENT BIGINT NOT NULL, RECEIVED BIGINT NOT NULL, VOLUME DOUBLE NOT NULL, SUCCESS BOOLEAN DEFAULT FALSE NOT NULL)"},
            // NPC_STATS
            {"CREATE CACHED TABLE IF NOT EXISTS NPC_STATS (ID INTEGER, SYS_X INTEGER NOT NULL, SYS_Y INTEGER NOT NULL, SYS_Z INTEGER NOT NULL, FLEET_SPAWNS INTEGER DEFAULT 0, ENTITY_SPAWNS INTEGER DEFAULT 0, PRIMARY KEY(ID,SYS_X,SYS_Y,SYS_Z))"},
            // PLAYER_MESSAGES (real StarMade schema)
            {"CREATE CACHED TABLE IF NOT EXISTS PLAYER_MESSAGES (ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY, SENDER VARCHAR(64) NOT NULL, RECEIVER VARCHAR(64) NOT NULL, TOPIC VARCHAR(128) NOT NULL, MESSAGE VARCHAR(1024) NOT NULL, SENT BIGINT NOT NULL, READ BOOLEAN DEFAULT FALSE, ATT_ID BIGINT)"},
            {"CREATE INDEX IF NOT EXISTS PM_SENDER ON PLAYER_MESSAGES(SENDER)"},
            {"CREATE INDEX IF NOT EXISTS PM_RECEIVER ON PLAYER_MESSAGES(RECEIVER)"},
            // MINES (real StarMade schema)
            {"CREATE CACHED TABLE IF NOT EXISTS MINES (ID INTEGER NOT NULL PRIMARY KEY, OWNER BIGINT NOT NULL, FACTION INTEGER DEFAULT 0 NOT NULL, HP SMALLINT NOT NULL, COMPOSITION SMALLINT ARRAY[6] NOT NULL, SECTOR_X INTEGER NOT NULL, SECTOR_Y INTEGER NOT NULL, SECTOR_Z INTEGER NOT NULL, LOCAL_X DOUBLE NOT NULL, LOCAL_Y DOUBLE NOT NULL, LOCAL_Z DOUBLE NOT NULL, CREATION_DATE BIGINT NOT NULL, ARMED BOOLEAN DEFAULT FALSE NOT NULL, ARMED_IN_SECS INTEGER DEFAULT -1 NOT NULL, AMMO SMALLINT DEFAULT -2 NOT NULL)"},
            {"CREATE INDEX IF NOT EXISTS IN_OWNER ON MINES(OWNER)"},
            {"CREATE INDEX IF NOT EXISTS IN_SECTOR ON MINES(SECTOR_X,SECTOR_Y,SECTOR_Z)"},
            // TEST_DDL (used by SchemaAnalyzer tests - 17th table)
            {"CREATE CACHED TABLE IF NOT EXISTS TEST_DDL (ID INTEGER PRIMARY KEY, NAME VARCHAR(50))"},
        };

        int created = 0;
        for (String[] row : ddl) {
            try (Statement s = conn.createStatement()) {
                s.execute(row[0]);
                created++;
            } catch (SQLException e) {
                if (!e.getMessage().contains("already exists")) {
                    System.out.println("DDL ERR: " + e.getMessage().substring(0, Math.min(100, e.getMessage().length())));
                }
            }
        }
        System.out.println("Schema created (" + created + " statements)");
    }
}
